add upgrades attributes for traveler-electro
genshindev/api pull request #154
Opened 2022-05-23 06:04 UTC by Nielioo

2022-06-20 12:44 UTC, JMPJNS requested changes, later dismissed

2022-06-20 12:44 UTC, JMPJNS commented on assets/data/characters/traveler-electro/en.json
> +      ],"type": "NORMAL_ATTACK"
add newline after ],

2022-06-20 12:44 UTC, JMPJNS commented on assets/data/characters/traveler-electro/en.json
> +      ],"type": "ELEMENTAL_SKILL"
add newline

2022-06-20 12:44 UTC, JMPJNS commented on assets/data/characters/traveler-electro/en.json
> +      ],"type": "ELEMENTAL_BURST"
add newline

2024-05-13 17:38 UTC, man90es commented
Another PR with the same data has been merged, but looks like this one has more correct values for some of the stats

2024-05-13 21:43 UTC, M4GICB approved these changes

2024-05-14 16:20 UTC, merged