Add 4.4 weapons and outfits
genshindev/api pull request #264
Opened 2024-02-28 18:24 UTC by majkus522

2024-05-11 14:20 UTC, M4GICB commented on assets/data/characters/ganyu/en.json
> +      "image": "outfit-twilight-blossom"
[rarity should be 4](https://genshin-impact.fandom.com/wiki/Twilight_Blossom)

2024-05-11 14:20 UTC, M4GICB commented on assets/data/characters/shenhe/en.json
> +      "image": "outfit-frostflower-dew"
[rarity should be 4](https://genshin-impact.fandom.com/wiki/Frostflower_Dew)

2024-05-11 14:43 UTC, M4GICB requested changes
needs a couple edits on rarities

2024-05-14 18:02 UTC, majkus522 commented
Fixed

2024-05-14 18:03 UTC, M4GICB approved these changes

2024-05-14 18:04 UTC, merged