Add missing outfits
genshindev/api pull request #270
Opened 2024-03-20 18:59 UTC by majkus522

2024-05-11 14:34 UTC, M4GICB commented on assets/data/characters/ayaka/en.json
> +      "image": "outfit-springbloom-missive"
[type should be Travel](https://genshin-impact.fandom.com/wiki/Springbloom_Missive)

2024-05-11 14:34 UTC, M4GICB commented on assets/data/characters/jean/en.json
> +      "image": "outfit-gunnhildr-s-legacy"
[rarity should be 4](https://genshin-impact.fandom.com/wiki/Gunnhildr%27s_Legacy)

2024-05-11 14:34 UTC, M4GICB commented on assets/data/characters/mona/en.json
> +      "image": "outfit-pact-of-stars-and-moon"
[rarity should be 4](https://genshin-impact.fandom.com/wiki/Pact_of_Stars_and_Moon)

2024-05-11 14:42 UTC, M4GICB requested changes
needs a few edits on rarities

2024-05-14 18:05 UTC, majkus522 commented
Fixed

2024-05-14 18:07 UTC, M4GICB approved these changes

2024-05-14 18:07 UTC, merged