Character images
genshindev/api pull request #288
Opened 2024-07-19 04:13 UTC by myun11

Changed some icons.

2024-07-19 17:31 UTC, man90es requested changes

2024-07-19 17:31 UTC, man90es commented on assets/images/characters/sethos/talent-burst
This isn't Sethos's burst icon

2024-07-19 17:31 UTC, man90es commented on assets/images/characters/candace/talent-passive-0
This is passive 3, not 0. The rest of passives' images need to be renamed accordingly too

2024-07-19 18:07 UTC, myun11 commented on assets/images/characters/candace/talent-passive-0
https://genshin-impact.fandom.com/wiki/Candace#Talents

I thought "Utility Passive" is talent-passive-0, "1st Ascension Passive" is talent-passive-1 and "4th Ascension Passive" is talent-passive-2

2024-07-19 18:08 UTC, myun11 commented on assets/images/characters/sethos/talent-burst
Fixed.

2024-07-20 14:38 UTC, man90es commented on assets/images/characters/candace/talent-passive-0
I have no idea why that would be the case, but looking at images we already have, it apparently is

2024-07-20 14:39 UTC, man90es approved these changes
Looks good, thanks for your contribution!

2024-07-20 14:39 UTC, merged