Added ascension materials for some characters
genshindev/api pull request #297
Opened 2024-08-13 08:30 UTC by myun11

Added ascension materials for Albedo, Alhaitham, Aloy, Amber, Arataki Itto, Ayaka, Ayato, Baizhu, Barbara, Beidou, Bennett.

The json structure is separated by ascension level, the name of the material and the quantity of the material. I can do this for all characters later on.

2024-08-20 21:58 UTC, man90es requested changes

2024-08-20 21:58 UTC, man90es commented on assets/data/characters/dori/en.json
> +        "name": "Shivada Jade Sliver",
Dori uses Vajrada Amethyst

2024-08-20 21:58 UTC, man90es commented on assets/data/characters/dori/en.json
> +        "name": "Calla Lily",
Dori uses Kalpalata Lotus

2024-08-20 21:58 UTC, man90es commented on assets/data/characters/dori/en.json
> +        "name": "Firm Arrowhead",
Dori uses Red Satin

2024-08-20 23:17 UTC, myun11 commented
Fixed Dori's ascension_materials.

2024-08-21 16:15 UTC, man90es approved these changes
Looks good to me, waiting for @M4GICB's review

2024-08-21 23:56 UTC, M4GICB approved these changes
Data all looks good. I only have 1 suggestion:
- `phase_1` - `phase_6` would make more sense than `level_20` - `level_80`
- This would make it so that the data shows the cost of unlocking `ascension phase x` rather than the cost of surpassing `level x`

If others disagree i am fine with this being merged though.

2024-08-22 19:06 UTC, man90es commented
> * `phase_1` - `phase_6` would make more sense than `level_20` - `level_80`
> * This would make it so that the data shows the cost of unlocking `ascension phase x` rather than the cost of surpassing `level x`

Idk honestly, I think both ways is fine

2024-08-28 04:25 UTC, myun11 commented
I think it's fine. Can always reflect that on the front end.

2024-08-28 16:47 UTC, merged