New 5.0 Characters
genshindev/api pull request #312
Opened 2024-09-06 08:13 UTC by keihachimaru

Addition of information about Kachina, Mualani, and Kinich in english. Kinich information is not yet complete, because he has not been released yet.

2024-09-06 13:20 UTC, niktekusho commented
Fixes #310 😉

2024-09-06 22:18 UTC, man90es requested changes
Please add Kinich data from this page: https://gensh.honeyhunterworld.com/kinich_101/?lang=EN

His release date is 18 September

2024-09-07 17:41 UTC, keihachimaru commented
Ok, I've added them. Also I added Mualani's Talents upgrades info.

2024-09-08 06:32 UTC, man90es requested changes

2024-09-08 06:32 UTC, man90es commented on assets/data/characters/kinich/en.json
> +    "release": "",
18 September 2024

2024-09-08 06:32 UTC, man90es commented on assets/data/characters/kinich/en.json
> +    "birthday": "",
11 November

2024-09-09 00:13 UTC, M4GICB requested changes
It would also be good to get these new character added to the talent material lists

2024-09-11 17:00 UTC, man90es approved these changes

2024-09-11 17:01 UTC, man90es commented
@M4GICB I didn't look at the latest commit, leaving it to you since you requested it. The rest looks good to me

2024-09-16 23:03 UTC, M4GICB approved these changes

2024-09-16 23:03 UTC, merged